travis:
  secure:
    BINSTAR_TOKEN: 8FJH2nNnemG4fleSzv3wFlWECoToU2+WhPOKMlQFYAXpSIV385CQoJRbI/ClcirwhGVwyXwUyUuHlwePZCQEPHVY0vfLhVFYGgt2ZogNSd4fltUsxSxguaaofxlUGIlczAy4l1Zr+MvEiGYCX26Ee0G6FX1tX6oVZJwlk3wtrkBTr4/XKLD++DyQ2FWg2jGu1tZDV8jbXA16bMCp9WXKpQlAhzWL8BNTr4xIWkwE9ITxPBwRWqE1nmvdQwFAnJHhHalH4FXuR63u2AAbJjg7rZTAiKBwRjHx7jUIy7ywDKQ/YZvoDTK9LkMKD+04O0Kar37U8HmXAXG0w8CxFRP3b9W5V9kXqVFzT55KPc2tVOU4YMBDji9XwQOMCHyNRL6ttFlOlO1WxFmf21YzNdDI+apXt1VLAUh4jcmcADqA8xQ89Iy1+bd/w2xu41XdOOKoPkap2Da68+9OaLm7e54zTGQrn9Dj2iwE5Qie5NZJzLof6/S4Mzxe2iUvqTctlNINGkAG9IJ8G5WSkerw4TXRGurnys1ZI5/f6iPsvTZBJvllCRXkKtjLprduyPsDy9VLknUXD02NY1Oo+g61FtCYNigMrQofnGN2fW0SD0pggh6ybGiEHr6bnHq+CVqoi6gaOEJMIo4mm69w+cX6iFF9Kla66qEzyfR3ltKQzTXSgA8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
