travis:
  secure:
    BINSTAR_TOKEN: vJM8FB9uqKypOSFepmx8u64n+biSXuhT0gMbCxEwOdu8YtJ0kBCnpQthbhbhDoSTUgxQJGkCgyA0wy31sGKM492XK3y6L6L0G9o4XN4RN7Sr1xbVdfpGw03d7wCXS1jnhbyPLxOPCGLWbO+A1WvkAs9A/A8dFzpumRSrHvdnAMyMLYB6PtWotDn4NiLLfMB6U/VthdjARePPymZjGBmX5CYO0pPbEnmYimNtssPcowJf33XeGiqtdk+M7NbyLznWsO5oeChOiH50qGk5HITAnvR8WSKWqvjFxlpI0CDnLBQQ3ugOxZFLo7QeqiG7SGSMvMQUDH8XXisNfV2eI42EblW37cbCisj4qrKowM0Y7Vw1WZ4cDGHtFLoTk7I8Cf3gd20Z+KRZl6x6XsaIdUVNvHJrRymGvGC/d35ke/yjEE1VTmPhyt3FX1Jmotr09XLgYQZZVPsoW4VWFgvnXWBwBrBeWQRQvyITfW+17RNFNxXQYGjDyBD3mhzBK7dIRcmjoxVhQY3qKVmC2lHPwn0rrvYIww22od1LKiXYGv3NWuToSilTQ+9hzXPJcRHKNz3RzAVZopwwdZFbq6TiNL4eZUiX0V/OGJU9LmWsqV68CvdPxGgOuK0DQl4g8hkgsJqE6ugVTq8uixJtd0F2XBrXJdX8K+2Mcuk229fEQoMemyg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
